services:
  - type: web
    name: booknestlib-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      alembic stamp head
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:10000
