"""Final models with correct timestamps

Revision ID: 79d93c885cd5
Revises: 
Create Date: 2025-07-08 02:54:43.107806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d93c885cd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('languages',
    sa.Column('LanguageID', sa.Integer(), nullable=False),
    sa.Column('LanguageName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('LanguageID'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_languages_LanguageID'), 'languages', ['LanguageID'], unique=False)
    op.create_index(op.f('ix_languages_LanguageName'), 'languages', ['LanguageName'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_name', sa.String(length=50), nullable=True),
    sa.Column('shelf_number', sa.String(length=20), nullable=True),
    sa.Column('section_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.LanguageID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)
    op.create_index(op.f('ix_subcategories_name'), 'subcategories', ['name'], unique=False)
    op.create_table('users',
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Username', sa.String(length=100), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('DateJoined', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RoleID'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('ClientID'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_ClientID'), 'users', ['ClientID'], unique=False)
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Username'), 'users', ['Username'], unique=True)
    op.create_table('book_copies',
    sa.Column('CopyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('LocationID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['BookID'], ['books.id'], ),
    sa.ForeignKeyConstraint(['LocationID'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('CopyID'),
    mysql_engine='InnoDB'
    )
    op.create_table('book_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.ClientID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('book_subcategory_link',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'subcategory_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('digital_access',
    sa.Column('DigitalAccessID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('AccessGranted', sa.Boolean(), nullable=True),
    sa.Column('AccessTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BookID'], ['books.id'], ),
    sa.ForeignKeyConstraint(['ClientID'], ['users.ClientID'], ),
    sa.PrimaryKeyConstraint('DigitalAccessID'),
    mysql_engine='InnoDB'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_by_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_by_id'], ['users.ClientID'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('upload_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='request_status_enum'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.ClientID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.ClientID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_upload_requests_id'), 'upload_requests', ['id'], unique=False)
    op.create_table('issued_books',
    sa.Column('IssuedBookID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('CopyID', sa.Integer(), nullable=False),
    sa.Column('IssueDate', sa.DateTime(), nullable=False),
    sa.Column('ReturnDate', sa.DateTime(), nullable=False),
    sa.Column('ActualReturnDate', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['users.ClientID'], ),
    sa.ForeignKeyConstraint(['CopyID'], ['book_copies.CopyID'], ),
    sa.PrimaryKeyConstraint('IssuedBookID'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_books')
    op.drop_index(op.f('ix_upload_requests_id'), table_name='upload_requests')
    op.drop_table('upload_requests')
    op.drop_table('logs')
    op.drop_table('digital_access')
    op.drop_table('book_subcategory_link')
    op.drop_table('book_permissions')
    op.drop_table('book_copies')
    op.drop_index(op.f('ix_users_Username'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_index(op.f('ix_users_ClientID'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subcategories_name'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_languages_LanguageName'), table_name='languages')
    op.drop_index(op.f('ix_languages_LanguageID'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
